Add Marker Module
tangrams/tangram-android-demos pull request #2
Opened 2016-11-02 18:33 UTC by sarahlensing

Adds a new module for demonstrating dynamic marker APIs

Demonstrates:
- Adding markers
- Toggling marker visibility
- Adding point markers
- Adding bitmap markers
- Adding polyline markers
- Adding polygon markers
- Removing markers

Depends on: https://github.com/tangrams/tangram-es/pull/1056

2016-12-07 21:56 UTC, tallytalwar commented on dynamicmarkers/build.gradle
> +    compile 'com.mapzen.tangram:tangram:0.4.4-SNAPSHOT'
This needs updating now.

2016-12-07 21:58 UTC, tallytalwar commented
Sorry for not reviewing this uptill now.

All this code looks good. But seems like scene file is not being loaded and hence no map gets displayed. Probably to do with the updates of handling the Urls in tangram.

2016-12-07 21:58 UTC, tallytalwar requested changes

2016-12-07 21:58 UTC, tallytalwar commented on dynamicmarkers/build.gradle
> +    compile 'com.mapzen.tangram:tangram:0.4.4-SNAPSHOT'
This needs updating now.

2016-12-13 19:54 UTC, sarahlensing commented on dynamicmarkers/build.gradle
> +    compile 'com.mapzen.tangram:tangram:0.4.4-SNAPSHOT'
Updated to 0.4.6!

2016-12-21 01:49 UTC, merged